# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

controllers:
  resource:
    path: ../src/Infrastructure/Web/Controller/
    namespace: App\Infrastructure\Web\Controller
  type: attribute
